### ISSUE TITLE
python -m explorer error

### ISSUE THREAD

**Issue by Danier-Evens** [taowen/es-monitor#3]
As HTTP Api Start http server (gunicorn) have some error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/hdfs/danier/project/es-monitor/explorer/__main__.py", line 14, in <module>
    '--error-logfile', 'log/error.log'] + sys.argv[1:])
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by Danier-Evens** [comment]
have already been solved.
